version: '2'
services:
  elasticsearch1:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
    container_name: elasticsearch1
    environment:
      - cluster.name=logcollector-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - xpack.security.enabled=false
      - TZ=Asia/Shanghai
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ~/docker/data/elasticsearch1/data/:/usr/share/elasticsearch/data
    ports:
      - 9222:9200
      - 9333:9300
    networks:
      fanshunet:
        ipv4_address: 192.168.1.11

networks:
    fanshunet:
        external:
            name: fanshunet

