version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      fanshunet:
        ipv4_address: ${ZOOKEEPER_ADDRESS}
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.11-1.0.2
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=${ZOOKEEPER_ADDRESS}:2181
      - KAFKA_LISTENERS=PLAINTEXT://${KAFKA_ADV_HOST}:9092
    ports:
      - "${KAKFA_OUT_PORT}:9092"
    depends_on:
      - zookeeper
    networks:
      fanshunet:
        ipv4_address: ${KAFKA_ADDRESS}
networks:
  fanshunet:
    external:
      name: fanshunet
