version: '3'
services:
  mysql-master:
    container_name: mysql-master
    image: mysql:8.0.13
    volumes:
      - ./master/cnf:/etc/mysql/conf.d
      - ./master/data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=fanshu@2018
    ports:
      - "3306:3306"
    networks:
      fanshunet:
        ipv4_address: 192.168.1.21
  mysql-slave:
    container_name: mysql-slave
    image: mysql:8.0.13
    volumes:
      - ./slave/cnf:/etc/mysql/conf.d
      - ./slave/data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=fanshu@2018
    ports:
      - "3307:3306"   
    networks:
      fanshunet:
        ipv4_address: 192.168.1.22
networks:
    fanshunet:
        external:
          name: fanshunet